In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns = ['cgpa','profile_score','lpa'])
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
def initialise_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1,L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))


    return parameters

initialise_parameters([2,2,1])


{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [5]:
def linear_forward(A_prev , W, b):
    Z = np.dot(W.T, A_prev) + b
    return Z

In [23]:
# Forward Propagation

def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) //2    #no. of layers in the neural network

    for l in range(1, L+1):
        A_prev = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        # print("A" + str(l-1)+ ": ", A_prev)
        # print("W" + str(l) + ": ", Wl)
        # print("b" + str(l) + ": ", bl)
        # print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
        # print("A" + str(l) + ": ", A)
        # print("**"*20)

    return A, A_prev




In [9]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # shape(no. of features, no. of training examples)
y = df[['lpa']].values[0][0]
print(y)
# parameter initialisation
parameters = initialise_parameters([2,2,1])
parameters

4


{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [11]:
y_hat, A1 = L_layer_forward(X, parameters)
# phle student k lia prediction
# A2 --> final prediction

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [15]:
print(y_hat,',' ,A1)


0.32000000000000006 , [[1.6]
 [1.6]]


In [16]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [17]:
update_parameters(parameters, y, y_hat, A1, X)
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [19]:
# for second student
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # shape(no. of features, no. of training examples)
y = df[['lpa']].values[1][0]


y_hat, A1 = L_layer_forward(X, parameters)

update_parameters(parameters, y, y_hat, A1, X)
parameters

A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************


{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [20]:
# for third student
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # shape(no. of features, no. of training examples)
y = df[['lpa']].values[2][0]


y_hat, A1 = L_layer_forward(X, parameters)

update_parameters(parameters, y, y_hat, A1, X)
parameters

A0:  [[ 6]
 [10]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.83539945]
 [1.87200826]]
****************************************
A1:  [[1.83539945]
 [1.87200826]]
W2:  [[0.12712927]
 [0.12712927]]
b2:  [[0.13612818]]
----------------------------------------
A2:  [[0.6074482]]
****************************************


{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

In [21]:
# for forth student
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # shape(no. of features, no. of training examples)
y = df[['lpa']].values[3][0]


y_hat, A1 = L_layer_forward(X, parameters)

update_parameters(parameters, y, y_hat, A1, X)
parameters

A0:  [[ 5]
 [12]]
W1:  [[0.12409711 0.13272353]
 [0.12412266 0.13276611]]
b1:  [[0.00355129]
 [0.00355555]]
----------------------------------------
A1:  [[2.11350869]
 [2.26036654]]
****************************************
A1:  [[2.11350869]
 [2.26036654]]
W2:  [[0.14692424]
 [0.14731907]]
b2:  [[0.15810417]]
----------------------------------------
A2:  [[0.80162493]]
****************************************


{'W1': array([[0.13482804, 0.15847776],
        [0.1349909 , 0.15884991]]),
 'b1': array([[0.00569748],
        [0.0057292 ]]),
 'W2': array([[0.17312488],
        [0.17534027]]),
 'b2': array([[0.18773702]])}

In [24]:
# epochs implementation

parameters = initialise_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

In [25]:
# using tensorflow
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(2,activation='linear', input_dim = 2))
model.add(Dense(1,activation='linear'))

c:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()
# keras m randomly initialise hote h ye weights.

[array([[ 0.15805244, -0.700654  ],
        [-0.07210875, -0.43862695]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.7658028],
        [-1.0160458]], dtype=float32),
 array([0.], dtype=float32)]

In [29]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error', optimizer = optimizer)

model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose = 1,batch_size = 1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7332  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.9332 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.7256 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.4948 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 10.0084
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.4969
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5692
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.0302 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.1876 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8060 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.4552 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.3115 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.1681 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.3638 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.6344
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━

In [31]:
model.get_weights()

[array([[ 0.25705624, -0.60688746],
        [-0.0097221 , -0.37749982]], dtype=float32),
 array([0.0819527 , 0.07865193], dtype=float32),
 array([[-0.8827133 ],
        [-0.93675286]], dtype=float32),
 array([-0.07999676], dtype=float32)]